version: "3.7"
services:
  app:
    build:
      args:
        user: nady
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: courses
    container_name: courses-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - courses
    depends_on:
      - db
      - nginx

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: courses-db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - ./docker-compose/mysql/config:/etc/mysql/conf.d
    networks:
      - courses

  nginx:
    image: nginx:alpine
    container_name: courses-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - courses

networks:
  courses:
    driver: bridge
